gouvernorat_index:
    path:     /
    defaults: { _controller: "SanteBundle:Gouvernorat:index" }
    methods:  GET

gouvernorat_show:
    path:     /{idGouvernorat}/show
    defaults: { _controller: "SanteBundle:Gouvernorat:show" }
    methods:  GET

gouvernorat_new:
    path:     /new
    defaults: { _controller: "SanteBundle:Gouvernorat:new" }
    methods:  [GET, POST]

gouvernorat_edit:
    path:     /{idGouvernorat}/edit
    defaults: { _controller: "SanteBundle:Gouvernorat:edit" }
    methods:  [GET, POST]

gouvernorat_delete:
    path:     /{idGouvernorat}/delete
    defaults: { _controller: "SanteBundle:Gouvernorat:delete" }
    methods:  DELETE
