user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Default:register }

user_profile:
    path:     /profile
    defaults: { _controller: UserBundle:FOSUser:profile }
